# Solo RRT Parameters
solo: {
  step_size: 1.3,
  obs_threshold: 0.23,

  xybuffer: -0.0,
  zbuffer: 2.0,
  passage_size: 3.5,

  min_height: 1.1,
  max_height: 1.9,

  max_tries: 25,
  timeout: 1.5,
  z_scale: 1.0
}

# Formation RRT Parameters
formation: {
  step_size: 1.8,
  obs_threshold: 5.4,

  xybuffer: 0.0,
  zbuffer: 4.75,
  passage_size: 0.25,

  min_height: 1.0,
  max_height: 4.75,

  max_tries: 25,
  timeout: 1.0,
  z_scale: 5.4
}
